// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PostgreMigrationPOC.Infrastructure.SqlServer.Data;

#nullable disable

namespace PostgreMigrationPOC.Infrastructure.SqlServer.Migrations
{
    [DbContext(typeof(SqlServerDbContext))]
    partial class SqlServerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PostgreMigrationPOC.Core.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("PostgreMigrationPOC.Core.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("BigIntField")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("BinaryField")
                        .HasColumnType("binary(16)");

                    b.Property<bool>("BooleanField")
                        .HasColumnType("bit");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CharField")
                        .IsRequired()
                        .HasColumnType("char(10)");

                    b.Property<DateOnly>("DateField")
                        .HasColumnType("date");

                    b.Property<DateTime>("DateTime2Field")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateTimeField")
                        .HasColumnType("datetime");

                    b.Property<DateTimeOffset>("DateTimeOffsetField")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("DecimalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("FloatField")
                        .HasColumnType("float");

                    b.Property<string>("GeographyField")
                        .HasColumnType("geography");

                    b.Property<string>("GeometryField")
                        .HasColumnType("geometry");

                    b.Property<Guid>("GuidField")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HierarchyIdField")
                        .HasColumnType("hierarchyid");

                    b.Property<decimal>("MoneyField")
                        .HasColumnType("money");

                    b.Property<string>("NcharField")
                        .IsRequired()
                        .HasColumnType("nchar(5)");

                    b.Property<string>("NtextField")
                        .HasColumnType("ntext");

                    b.Property<string>("NvarcharField")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<float>("RealField")
                        .HasColumnType("real");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("SmallDateTimeField")
                        .HasColumnType("smalldatetime");

                    b.Property<short>("SmallIntField")
                        .HasColumnType("smallint");

                    b.Property<decimal>("SmallMoneyField")
                        .HasColumnType("smallmoney");

                    b.Property<string>("TextField")
                        .HasColumnType("text");

                    b.Property<TimeOnly>("TimeField")
                        .HasColumnType("time");

                    b.Property<byte>("TinyIntField")
                        .HasColumnType("tinyint");

                    b.Property<byte[]>("VarbinaryField")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("VarcharField")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("XmlField")
                        .HasColumnType("xml");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("PostgreMigrationPOC.Core.Entities.ProductDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DetailedDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManufacturerInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Specifications")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("ProductDetails", (string)null);
                });

            modelBuilder.Entity("PostgreMigrationPOC.Core.Entities.ProductTag", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("ProductId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("ProductTags", (string)null);
                });

            modelBuilder.Entity("PostgreMigrationPOC.Core.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags", (string)null);
                });

            modelBuilder.Entity("PostgreMigrationPOC.Core.Entities.Product", b =>
                {
                    b.HasOne("PostgreMigrationPOC.Core.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PostgreMigrationPOC.Core.Entities.ProductDetail", b =>
                {
                    b.HasOne("PostgreMigrationPOC.Core.Entities.Product", "Product")
                        .WithOne("ProductDetail")
                        .HasForeignKey("PostgreMigrationPOC.Core.Entities.ProductDetail", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PostgreMigrationPOC.Core.Entities.ProductTag", b =>
                {
                    b.HasOne("PostgreMigrationPOC.Core.Entities.Product", "Product")
                        .WithMany("ProductTags")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PostgreMigrationPOC.Core.Entities.Tag", "Tag")
                        .WithMany("ProductTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("PostgreMigrationPOC.Core.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("PostgreMigrationPOC.Core.Entities.Product", b =>
                {
                    b.Navigation("ProductDetail");

                    b.Navigation("ProductTags");
                });

            modelBuilder.Entity("PostgreMigrationPOC.Core.Entities.Tag", b =>
                {
                    b.Navigation("ProductTags");
                });
#pragma warning restore 612, 618
        }
    }
}
